server:
  port: 8080
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: digitalKids
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.digital.entity
config:
  jwt:
    # 加密密钥
    secret: digitalKids
    # token有效时长
    expire: 3600
    # header 名称
    header: token
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: digitalKids-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000