server:
  port: 8081
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: digitalKids
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.digital.entity
config:
  jwt:
    # 加密密钥
    secret: digitalKids
    # token有效时长
    expire: 3600
    # header 名称
    header: token
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: digitalKids-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
#        // 序列化、反序列化一致
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s
#    rest:
#      username: elastic
#      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    database: 15
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


