spring:
  application:
    name: mcp
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/digitalKids
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    mcp:
      server:
        enabled: true
        name: book-management-server
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/message
  ai:
    openai:
      api-key: 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


server:
  port: 7777